#!/bin/bash

echo "🎓 CurriculumBank - Available Commands"
echo "======================================"
echo ""

echo "📋 Setup & Development:"
echo "  ./simple-start.sh       - Start in development mode (separate terminals)"
echo "  ./quick-start.sh        - Automated setup and start"
echo "  ./start-dev.sh          - Development mode with auto-restart"
echo ""

echo "🐳 Docker & Deployment:"
echo "  ./fix-docker.sh         - Fix Docker build issues (run first!)"
echo "  ./test-docker.sh        - Test Docker builds"
echo "  docker-compose up       - Start with Docker"
echo "  docker-compose up -d    - Start with Docker (background)"
echo "  ./deploy.sh             - Production deployment"
echo ""

echo "🧪 Testing:"
echo "  ./run-tests.sh          - Run all tests"
echo "  cd backend && npm test  - Backend tests only"
echo "  cd frontend && npm test - Frontend tests only"
echo ""

echo "🔧 Maintenance:"
echo "  ./verify-app.sh         - Verify application health"
echo "  ./validate-project.sh   - Complete project validation"
echo "  ./backup-db.sh          - Backup database"
echo "  ./update.sh             - Update application"
echo ""

echo "📋 Information:"
echo "  ./help.sh               - Show this help (current script)"
echo "  ./demo.sh               - Project demonstration"
echo ""

echo "📊 Access Points:"
echo "  Development: http://localhost:3000 (frontend)"
echo "  Production:  http://localhost (Docker)"
echo "  Backend API: http://localhost:5000/api"
echo "  Health:      http://localhost:5000/api/health"
echo ""

echo "📖 Documentation:"
echo "  README.md               - Main documentation"
echo "  DOCKER-SETUP.md         - Docker troubleshooting"
echo "  docs/                   - Complete documentation"
echo "  COMPLETION-REPORT.md    - Project completion status"
echo ""

echo "💡 Quick Start Recommendations:"
echo ""
echo "🎯 For Development:"
echo "   ./simple-start.sh"
echo ""
echo "🎯 For Docker/Production:"
echo "   ./fix-docker.sh && docker-compose up"
echo ""
echo "🎯 For Testing Everything:"
echo "   ./run-tests.sh && ./verify-app.sh"
